### ISSUE TITLE
Every download fails, even trying the example.

### ISSUE THREAD

**Issue by parkerlreed** [shakenfist/occystrap#12]
I don't know if something changed with the OCI layout or what, but everything I try says that it's an invalid manifest media type.

```
~ $ occystrap fetch-to-tarfile registry-1.docker.io library/busybox \
    latest busybox.tar
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/bin/occystrap", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/occystrap/main.py", line 92, in fetch_to_tarfile
    _fetch(registry, image, tag, tar, ctx.obj['OS'], ctx.obj['ARCHITECTURE'],
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/occystrap/main.py", line 38, in _fetch
    for image_element in img.fetch(fetch_callback=output.fetch_callback):
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/occystrap/docker_registry.py", line 120, in fetch
    raise Exception('Unknown manifest content type %s!' %
Exception: Unknown manifest content type application/vnd.oci.image.index.v1+json!
```

**Comment by mikalstill** [comment]
Sorry I didn't notice this issue earlier. Something has definitely changed to break downloads.

```
$ python3 -mvenv ~/virtualenvs/occystrap
$ . ~/virtualenvs/occystrap/bin/activate
$ python3 setup.py develop
$ occystrap fetch-to-tarfile registry-1.docker.io library/busybox latest busybox.tar
Traceback (most recent call last):
  File "/Users/mikal/virtualenvs/occystrap/bin/occystrap", line 10, in <module>
    sys.exit(cli())
             ^^^^^
  File "/Users/mikal/virtualenvs/occystrap/lib/python3.11/site-packages/click-8.1.7-py3.11.egg/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mikal/virtualenvs/occystrap/lib/python3.11/site-packages/click-8.1.7-py3.11.egg/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/Users/mikal/virtualenvs/occystrap/lib/python3.11/site-packages/click-8.1.7-py3.11.egg/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mikal/virtualenvs/occystrap/lib/python3.11/site-packages/click-8.1.7-py3.11.egg/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mikal/virtualenvs/occystrap/lib/python3.11/site-packages/click-8.1.7-py3.11.egg/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mikal/virtualenvs/occystrap/lib/python3.11/site-packages/click-8.1.7-py3.11.egg/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mikal/src/shakenfist/occystrap/occystrap/main.py", line 92, in fetch_to_tarfile
    _fetch(registry, image, tag, tar, ctx.obj['OS'], ctx.obj['ARCHITECTURE'],
  File "/Users/mikal/src/shakenfist/occystrap/occystrap/main.py", line 38, in _fetch
    for image_element in img.fetch(fetch_callback=output.fetch_callback):
  File "/Users/mikal/src/shakenfist/occystrap/occystrap/docker_registry.py", line 120, in fetch
    raise Exception('Unknown manifest content type %s!' %
Exception: Unknown manifest content type application/vnd.oci.image.index.v1+json!
```

**Comment by mikalstill** [comment]
The docker registry is now using the new OCI mime types: https://github.com/opencontainers/image-spec/blob/main/media-types.md

**Comment by parkerlreed** [comment]
Thanks!
